# fly.toml app configuration file generated for 2026-worldcup-agent on 2025-07-03T11:58:16+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '2026-worldcup-agent'
primary_region = 'nrt'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
